unique_name: Product Dimension
object_type: dimension
label: Product Dimension
description: "Product Line, Category, and Name"
type: standard

hierarchies:

  - unique_name: Product Dimension
    label: Product Hierarchy
    folder: Product Attributes

    levels:

      - unique_name: Product Line

      - unique_name: Product Category

        secondary_attributes:

          - unique_name: d_productsubcategoryId
            label: Product Subcategory ID
            description: ID of the product category
            dataset: dimproduct
            name_column: productsubcategorykey
            key_columns:
              - productsubcategorykey

      - unique_name: Product Name

        secondary_attributes:

          - unique_name: L2
            label: L2
            folder: Product Attributes
            dataset: dimproduct
            name_column: listprice
            key_columns:
              - listprice
            sort_column: listprice
            allowed_calcs_for_dma:
              - Lag
              - Range
              - Siblings

        metrics:

          - unique_name: List Price
            label: List Price
            calculation_method: sum
            folder: Product Metrics
            dataset: dimproduct
            column: listprice

level_attributes:

  - unique_name: Product Category
    label: Product Category
    description: Product Sub Category
    dataset: dimproduct
    name_column: productsubcategoryname
    key_columns:
      - productline
      - productsubcategorykey

  - unique_name: Product Line
    label: Product Line
    description: Product Line
    dataset: dimproduct
    name_column: productline
    key_columns:
      - productline

  - unique_name: Product Name
    label: Product Name
    description: Full Product Name
    is_unique_key: true
    dataset: dimproduct
    name_column: englishproductname
    key_columns:
      - productkey

modeler_metadata:
  version: 0
  modified: "false"
