unique_name: Product Dimension
object_type: dimension
label: Product Dimension
description: Product Line, Category, and Name
hierarchies:
  - unique_name: Product  Dimension Hierarchy
    label: Product Hierarchy
    folder: Product Attributes
    levels:
      - unique_name: Product Line
      - unique_name: Product Category
        secondary_attributes:
          - unique_name: d_productsubcategoryId
            label: Product Subcategory ID
            description: ID of the product category
            dataset: dimproduct
            key_columns:
              - productsubcategorykey
            name_column: productsubcategorykey
      - unique_name: Product Name
        metrics:
          - unique_name: List Price
            label: List Price
            calculation_method: sum
            column: listprice
            dataset: dimproduct
            folder: Product Metrics
        secondary_attributes:
          - unique_name: L2
            label: L2
            allowed_calcs_for_dma:
              - Lag
              - Siblings
              - Range
            dataset: dimproduct
            folder: Product Attributes
            key_columns:
              - listprice
            name_column: listprice
            sort_column: listprice
level_attributes:
  - unique_name: Product Category
    label: Product Category
    description: Product Sub Category
    dataset: dimproduct
    key_columns:
      - productline
      - productsubcategorykey
    name_column: productsubcategoryname
  - unique_name: Product Line
    label: Product Line
    description: Product Line
    dataset: dimproduct
    key_columns:
      - productline
    name_column: productline
  - unique_name: Product Name
    label: Product Name
    description: Full Product Name
    dataset: dimproduct
    is_unique_key: true
    key_columns:
      - productkey
    name_column: englishproductname
modeler_metadata:
  modified: 'false'
  version: 0
type: standard
